export enum JobEvents {
  START = `job.start`,
  STARTED = `job.started`,
  PAUSE = `job.pause`,
  PAUSED = `job.paused`,
  RESUME = `job.resume`,
  RESUMED = `job.resumed`,
  CANCEL = 'job.cancel',
  CANCELED = 'job.canceled',
  STOPPED = `job.stopped`,
  PREPARING = `job.preparing`,
  TASK_STARTED = 'job.task_started',
  TASK_COMPLETED = 'job.task_completed',
  TASK_FAILED = 'job.task_failed',
  COMPLETED = `job.completed`,
  FAILED = `job.failed`,
  CURRENT_PROGRESS = `job.current_progress`,
}
