import { useState } from 'react'
import type { Meta } from '@storybook/react'

import Modal from './Modal'
import ModalLayer from './ModalLayer'
import Button from '../../interaction/Button'
import WrittenText from '../../typography/WrittenText'

const meta = {
  title: 'Layout/Modal',
  component: Modal,
  argTypes: {},
} satisfies Meta<typeof Modal>

export const SmallContent = () => {
  const [isOpen, setIsOpen] = useState(false)

  return (
    <div>
      <ModalLayer />
      <div style={{ display: 'flex', gap: 15 }}>
        <Button onClick={() => setIsOpen(true)}>
          Open modal
        </Button>
      </div>
      {isOpen &&
        <Modal width={800} onClose={() => setIsOpen(false)}>
          <WrittenText>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <Button onClick={() => setIsOpen(false)}>Close modal</Button>
          </WrittenText>
        </Modal>
      }
    </div>
  )
}

export const BigContent = () => {
  const [isOpen, setIsOpen] = useState(false)

  return (
    <div>
      <ModalLayer />
      <div style={{ display: 'flex', gap: 15 }}>
        <Button onClick={() => setIsOpen(true)}>
          Open modal
        </Button>
      </div>
      {isOpen &&
        <Modal onClose={() => setIsOpen(false)}>
          <WrittenText>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <Button onClick={() => setIsOpen(false)}>Close modal</Button>
          </WrittenText>
        </Modal>
      }
    </div>
  )
}

export const Loading = () => {
  const [isOpen, setIsOpen] = useState(false)

  return (
    <div>
      <ModalLayer />
      <div style={{ display: 'flex', gap: 15 }}>
        <Button onClick={() => setIsOpen(true)}>
          Open modal
        </Button>
      </div>
      {isOpen &&
        <Modal loading={true} onClose={() => setIsOpen(false)}>
          <WrittenText>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas dictum commodo. Cras egestas massa in convallis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus pretium dui tempor feugiat fringilla. Etiam nec imperdiet lectus, varius consectetur ex. Aliquam dolor sapien, malesuada ut iaculis vel, rutrum eleifend lorem. Maecenas gravida arcu non orci sodales aliquet facilisis a risus. Aenean gravida nisl tellus, id pulvinar velit cursus vitae. Vivamus tempus congue aliquam. Sed convallis tincidunt rutrum. Phasellus eu vulputate dolor. Nullam dolor urna, viverra at enim vel, feugiat venenatis dui.</p>
            <Button onClick={() => setIsOpen(false)}>Close modal</Button>
          </WrittenText>
        </Modal>
      }
    </div>
  )
}

export default meta
